#!/usr/bin/env bash
set -euo pipefail

ROOT="$(pwd)"
WORK="$ROOT/.cf-build"
OUTPUT="$ROOT/dist"
BASE="$ROOT/releases/project-sovereign-v0.2.0-source.zip"
V03_PATCH="$WORK/guided-gameplay-v0.3.patch"
V04_BASE64="$WORK/project-sovereign-v0.4.0.patch.xz.b64"
V04_XZ="$WORK/project-sovereign-v0.4.0.patch.xz"
V04_PATCH="$WORK/project-sovereign-v0.4.0.patch"
V04_APPLY_PATCH="$WORK/project-sovereign-v0.4.0.apply.patch"
V05_XZ="$WORK/project-sovereign-v0.5.0.patch.xz"
V05_PATCH="$WORK/project-sovereign-v0.5.0.patch"
V05_APPLY_PATCH="$WORK/project-sovereign-v0.5.0.apply.patch"

printf 'PROJECT SOVEREIGN Cloudflare build v0.5.0\n'
printf 'Repository commit: %s\n' "$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

rm -rf "$WORK" "$OUTPUT"
mkdir -p "$WORK"
unzip -tqq "$BASE"
unzip -q "$BASE" -d "$WORK"
PROJECT="$WORK/project-sovereign"
test -f "$PROJECT/package.json"

# Reconstruct the verified v0.3 source.
shopt -s nullglob
V03_PARTS=("$ROOT"/releases/v0.3/guided-gameplay-v2.patch.part-*)
if (( ${#V03_PARTS[@]} != 6 )); then
  echo "ERROR: expected 6 v0.3 patch files, found ${#V03_PARTS[@]}." >&2
  exit 1
fi
cat "${V03_PARTS[@]}" > "$V03_PATCH"
cd "$PROJECT"
patch --batch --forward -p1 < "$V03_PATCH"

# Reconstruct and apply the verified v0.4 patch.
cd "$ROOT"
V04_PARTS=("$ROOT"/releases/v0.4/v04.patch.xz.b64.part-*)
if (( ${#V04_PARTS[@]} != 7 )); then
  echo "ERROR: expected 7 v0.4 patch files, found ${#V04_PARTS[@]}." >&2
  exit 1
fi
printf 'v0.4 patch parts: %s\n' "${#V04_PARTS[@]}"
cat "${V04_PARTS[@]}" | tr -d '\r\n\t ' > "$V04_BASE64"
base64 --decode "$V04_BASE64" > "$V04_XZ"
xz -t "$V04_XZ"
xz -dc "$V04_XZ" > "$V04_PATCH"

# package-lock.json is regenerated by npm install because the v0.3 archive has no lock file.
awk '
/^diff --git / { skip = ($0 == "diff --git a/package-lock.json b/package-lock.json") }
!skip { print }
' "$V04_PATCH" > "$V04_APPLY_PATCH"

cd "$PROJECT"
patch --batch --forward --dry-run -p1 < "$V04_APPLY_PATCH" >/dev/null
patch --batch --forward -p1 < "$V04_APPLY_PATCH"
echo 'v0.4 patch applied.'

# Reconstruct the verified v0.5 XZ from eight byte-exact Git blobs.
# No fixed SHA value and no Base64 reconstruction are used for v0.5.
cd "$ROOT"
V05_PARTS=("$ROOT"/releases/v0.5/chunks/part-*.bin)
if (( ${#V05_PARTS[@]} != 8 )); then
  echo "ERROR: expected 8 v0.5 binary chunks, found ${#V05_PARTS[@]}." >&2
  exit 1
fi
printf 'v0.5 binary chunks: %s\n' "${#V05_PARTS[@]}"
cat "${V05_PARTS[@]}" > "$V05_XZ"
printf 'v0.5 compressed patch bytes: %s\n' "$(wc -c < "$V05_XZ" | tr -d ' ')"
xz -t "$V05_XZ"
xz -dc "$V05_XZ" > "$V05_PATCH"
printf 'v0.5 text patch bytes: %s\n' "$(wc -c < "$V05_PATCH" | tr -d ' ')"

awk '
/^diff --git / { skip = ($0 == "diff --git a/package-lock.json b/package-lock.json") }
!skip { print }
' "$V05_PATCH" > "$V05_APPLY_PATCH"

cd "$PROJECT"
patch --batch --forward --dry-run -p1 < "$V05_APPLY_PATCH" >/dev/null
patch --batch --forward -p1 < "$V05_APPLY_PATCH"
echo 'v0.5 patch applied.'

for required in \
  src/gameplay/policy-direction.ts \
  src/gameplay/policy-effects.ts \
  src/gameplay/random-events.ts \
  src/gameplay/scheduled-events.ts \
  src/ui/policy-direction-view.ts \
  src/ui/turn-result-view.ts; do
  if [[ ! -f "$required" ]]; then
    echo "ERROR: required v0.5 source file is missing: $required" >&2
    exit 1
  fi
done

node -e "const p=require('./package.json'); if(p.version!=='0.5.0') process.exit(1)"
if [[ -f public/_redirects ]]; then
  echo 'ERROR: public/_redirects remains after applying v0.5.' >&2
  exit 1
fi

npm install --no-audit --no-fund
npm run verify

cd "$ROOT"
cp -a "$PROJECT/dist" "$OUTPUT"
rm -f "$OUTPUT/_redirects"
printf '_redirects\n' > "$OUTPUT/.assetsignore"

test -f "$OUTPUT/index.html"
test -f "$OUTPUT/src/ui/main.js"
test -f "$OUTPUT/src/ui/policy-direction-view.js"
test -f "$OUTPUT/src/ui/turn-result-view.js"
grep -q '4つの国家方針' "$OUTPUT/src/ui/policy-direction-view.js"
grep -q '現在選択中' "$OUTPUT/src/ui/policy-direction-view.js"
grep -q '自然変動' "$OUTPUT/src/ui/turn-result-view.js"
grep -q '方針による効果' "$OUTPUT/src/ui/turn-result-view.js"
grep -q '国家選択イベント' "$OUTPUT/src/ui/main.js"

if find "$OUTPUT" -type f -name '_redirects' -print -quit | grep -q .; then
  echo 'ERROR: _redirects still exists in deployment output.' >&2
  exit 1
fi

printf 'Deployment output verified: %s files; v0.5 tests and build passed.\n' "$(find "$OUTPUT" -type f | wc -l | tr -d ' ')"
